### ISSUE TITLE
Install Problem- /prepare.sh: line 2301: syntax error

### ISSUE THREAD

**Issue by whatguts** [qntmpkts/chroagh#1]
Hi qntmpkts. First, thank you for continuing work on chroagh, it gives people like me hope, that perhaps it really is possible to get Arch working (SeaBios has problems). I did encounter some hiccups during installation, your help is much appreciated.

Please paste the output of the following command here: sudo edit-chroot -all
> name: arch
> encrypted: no
> Entering /mnt/stateful_partition/crouton/chroots/arch...
> crouton: version git
> release: arch
> architecture: x86_64
> targets: xfce
> host: version 9765.31.0 (Official Build) beta-channel sentry 
> kernel: Linux localhost 3.18.0-15945-g3e5ac8a02327 #1 SMP PREEMPT Wed Aug 16 22:01:11 PDT 2017 x86_64 GNU/Linux
> freon: yes

#### Please describe your issue:
When Installing chroagh,. However, chroot was not able to install, instead I find a few warnings about missing modules and a syntax error.

> WARNING: Possibly missing firmware for module: wd719x
> WARNING: Possibly missing firmware for module: aic94xx

> /prepare.sh: line 2301: syntax error: unexpected end of file
> Failed to complete chroot setup.

> The chroot setup script may be broken. Your chroot is not fully configured.
> Removing the chroot setup script. You may want to update your chroot again.
> UID 1000 not found in arch

#### If known, describe the steps to reproduce the issue:
 I followed the exact steps in the readme file.
> cd ~/Downloads
> wget https://api.github.com/repos/qntmpkts/chroagh/tarball -O chroagh.tar.gz
> tar xvf chroagh.tar.gz
> cd qntmpkts-chroagh-*
> sudo sh -e installer/main.sh -r arch -t xfce

**Comment by qntmpkts** [comment]
Thanks for your report. I'll be working on this -- likely stems from a merge issue.

**Comment by whatguts** [comment]
Of course, let me know if any actions are necessary on my end.

**Comment by qntmpkts** [comment]
This is presently resolved. However, there are still issues with getting a fully working arch chroot running.
