### ISSUE TITLE
Black screen when using xiwi

### ISSUE THREAD

**Issue by markitoxs** [qntmpkts/chroagh#5]
```
name: archer
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/archer...
crouton: version git
release: arch
architecture: x86_64
xmethod: xiwi
targets: xiwi,cli-extra,keyboard
host: version 9901.54.0 (Official Build) stable-channel eve 
kernel: Linux localhost 4.4.79-11650-ge987f76b729a #1 SMP PREEMPT Tue Oct 24 23:57:37 PDT 2017 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/archer...
```

I am attempting to run i3 ( I've also tried xfce ) within xiwi.
There's something weird happening because whenever I execute xinit, it does indeed launch xiwi and such, but the screen remains black. To be clear, I know for a fact i3 is being executed, as I can open a terminal and 'blidly' type commands, even if I mod + shift + e and click in roughly the top right corner, I indeed exit i3 and return to the terminal. 

I've tried xfce and it's the same.

Strangely, root user works fine.

**Comment by qntmpkts** [comment]
Update your copy of chroagh and see if xfce works now. I just tested it with non-root and it works without problems.

**Comment by markitoxs** [comment]
sweet, Ill give that a shot. Thank you.

**Comment by qntmpkts** [comment]
If i3 still does not work, please open a separate issue.
